apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendImage.name }}
  namespace: app
spec:
  selector:
    matchLabels:
      app: {{ .Values.backendImage.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendImage.name }}
    spec:
      containers:
      - name: {{ .Values.backendImage.name }}
        image: {{ .Values.backendImage.reposistory }}
        ports:
        - containerPort: 80
