apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontendImage.name }}
  ports:
  - port: 80
    targetPort: 80
